apiVersion: v1
kind: Secret
metadata:
  name: trading-secrets
  namespace: trading-system
type: Opaque
data:
  JWT_SECRET_KEY: # base64 encoded secret key
  DB_PASSWORD: # base64 encoded database password
  EXCHANGE_API_KEY: # base64 encoded exchange API key
  EXCHANGE_SECRET_KEY: # base64 encoded exchange secret key
