apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: trading-system
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: decision-service
  namespace: trading-system
spec:
  selector:
    app: decision-service
  ports:
  - port: 8001
    targetPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: risk-service
  namespace: trading-system
spec:
  selector:
    app: risk-service
  ports:
  - port: 8002
    targetPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: trading-system
spec:
  selector:
    app: execution-service
  ports:
  - port: 8003
    targetPort: 8003
